/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/filterView`; params?: Router.UnknownInputParams; } | { pathname: `/menu`; params?: Router.UnknownInputParams; } | { pathname: `/quote`; params?: Router.UnknownInputParams; } | { pathname: `/quoteForm`; params?: Router.UnknownInputParams; } | { pathname: `/quotesView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/context/QuoteContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/SnackbarContext`; params?: Router.UnknownInputParams; } | { pathname: `/helper/AnimatedButton`; params?: Router.UnknownInputParams; } | { pathname: `/helper/animations`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/filterView`; params?: Router.UnknownOutputParams; } | { pathname: `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `/quote`; params?: Router.UnknownOutputParams; } | { pathname: `/quoteForm`; params?: Router.UnknownOutputParams; } | { pathname: `/quotesView`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/context/QuoteContext`; params?: Router.UnknownOutputParams; } | { pathname: `/context/SnackbarContext`; params?: Router.UnknownOutputParams; } | { pathname: `/helper/AnimatedButton`; params?: Router.UnknownOutputParams; } | { pathname: `/helper/animations`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/filterView${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `/quote${`?${string}` | `#${string}` | ''}` | `/quoteForm${`?${string}` | `#${string}` | ''}` | `/quotesView${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/context/QuoteContext${`?${string}` | `#${string}` | ''}` | `/context/SnackbarContext${`?${string}` | `#${string}` | ''}` | `/helper/AnimatedButton${`?${string}` | `#${string}` | ''}` | `/helper/animations${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/filterView`; params?: Router.UnknownInputParams; } | { pathname: `/menu`; params?: Router.UnknownInputParams; } | { pathname: `/quote`; params?: Router.UnknownInputParams; } | { pathname: `/quoteForm`; params?: Router.UnknownInputParams; } | { pathname: `/quotesView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/context/QuoteContext`; params?: Router.UnknownInputParams; } | { pathname: `/context/SnackbarContext`; params?: Router.UnknownInputParams; } | { pathname: `/helper/AnimatedButton`; params?: Router.UnknownInputParams; } | { pathname: `/helper/animations`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
